import pycpdf

pycpdf.loadDLL("/Users/john/repos/python-libcpdf/libpycpdf.so")

def prerr():
  print(f'({pycpdf.lastError()} | {pycpdf.lastErrorString()})')

#CHAPTER 0. Preliminaries
print('***** CHAPTER 0. Preliminaries')
print('---cpdf_startup()')
pycpdf.startup()
prerr()
print('---cpdf_version()')
print('version = ' + pycpdf.version())
prerr()
print('---cpdf_setFast()')
pycpdf.setFast()
prerr()
print('---cpdf_setSlow()')
pycpdf.setSlow()
prerr()
print('---cpdf_clearError()')
pycpdf.clearError()
prerr()
print('---cpdf_onExit()')
pycpdf.onExit()

#CHAPTER 1. Basics
print('***** CHAPTER 1. Basics')
print('---cpdf_fromFile()')
pdf = pycpdf.fromFile('cpdflibmanual.pdf', '')
prerr()
print('---cpdf_fromFileLazy')
pdf2 = pycpdf.fromFileLazy('testinputs/cpdfmanual.pdf', '')
prerr()
fh = open('testinputs/cpdfmanual.pdf', mode='rb')
data = fh.read()
print('---cpdf_fromMemory')
pdf3 = pycpdf.fromMemory(data, '')
prerr()
print('---cpdf_fromMemoryLazy')
pdf4 = pycpdf.fromMemoryLazy(data, '')
prerr()
print('---cpdf_blankDocument')
pdf5 = pycpdf.blankDocument(200.5, 100.0, 50)
prerr()
print('---cpdf_toFile')
pycpdf.toFile(pdf5, 'testoutputs/blank.pdf', False, False)
prerr()
print('---cpdf_blankDocumentPaper')
pdf6 = pycpdf.blankDocumentPaper(pycpdf.a3landscape, 50)
prerr()
pycpdf.toFile(pdf6, 'testoutputs/blank2.pdf', False, False)
print('---cpdf_deletePdf')
pycpdf.deletePdf(pdf)
prerr()
print('---cpdf_replacePdf')
pycpdf.replacePdf(pdf2, pdf3)
prerr()
print('---cpdf_enumeratePDFs')
pdfs = pycpdf.enumeratePDFs()
prerr()
for k, i in pdfs:
  print(k, i)
print('---cpdf_ptOfCm')
print(pycpdf.ptOfCm(1.0))
prerr()
print('---cpdf_ptOfMm')
print(pycpdf.ptOfMm(1.0))
prerr()
print('---cpdf_ptOfIn')
print(pycpdf.ptOfIn(1.0))
prerr()
print('---cpdf_cmOfPt')
print(pycpdf.cmOfPt(1.0))
prerr()
print('---cpdf_ptOfCm')
print(pycpdf.mmOfPt(1.0))
prerr()
print('---cpdf_ptOfCm')
print(pycpdf.inOfPt(1.0))
prerr()
print('---cpdf_parsePagespec')
r = pycpdf.parsePagespec(pdf4, "1-3,end")
prerr()
print('---cpdf_valiadatePagespec')
valid = pycpdf.validatePagespec("1-4,5,6")
prerr()
print('---cpdf_all')
allpdf4 = pycpdf.all(pdf4)
prerr()
print(allpdf4)
print('---cpdf_stringOfPagespec')
pagespecstr = pycpdf.stringOfPagespec(pdf4, allpdf4)
prerr()
print(pagespecstr)
print('---cpdf_blankRange')
blankrange = pycpdf.blankRange()
prerr()
print('---cpdf_pageRange')
fromto = pycpdf.pageRange(3, 7)
print('---cpdf_all')
rall = pycpdf.all(pdf4)
prerr()
print("all", rall)
print('---cpdf_even')
even = pycpdf.even(rall)
prerr()
print('---cpdf_odd')
odd = pycpdf.odd(rall)
prerr()
print('---cpdf_rangeUnion')
union = pycpdf.rangeUnion(even, odd)
prerr()
print('---cpdf_difference')
difference = pycpdf.difference(even, odd)
prerr()
print('---cpdf_removeDuplicates')
nodeps = pycpdf.removeDuplicates(rall)
prerr()
print('---cpdf_rangeLength')
rangel = pycpdf.rangeLength(union)
prerr()
print('---cpdf_rangeGet')
got = pycpdf.rangeGet(odd, 1)
prerr()
print('---cpdf_rangeAdd')
added = pycpdf.rangeAdd(odd, 9)
prerr()
print('---cpdf_isInRange')
inrange = pycpdf.isInRange(odd, 1)
prerr()
print('---cpdf_pages')
pages = pycpdf.pages(pdf5)
prerr()
print('---cpdf_pagesFast')
pagesf = pycpdf.pagesFast('', 'testinputs/cpdfmanual.pdf')
prerr()
print('---cpdf_toFile')
pycpdf.toFile(pdf4, 'testoutputs/toFile.pdf', False, False)
prerr()
print('---cpdf_toFileExt')
pycpdf.toFileExt(pdf4, 'testoutputs/toFileExt.pdf', False, False, False, False, False)
prerr()
print('---cpdf_toMemory')
tomembytes = pycpdf.toMemory(pdf5, False, False)
prerr()
print('---cpdf_isEncrypted')
isenc = pycpdf.isEncrypted(pdf5)
prerr()
print('---cpdf_toFileEncrypted')
pycpdf.toFileEncrypted(pdf5, pycpdf.pdf40bit, [pycpdf.noEdit], 'owner', 'user', False, False, 'testoutputs/enc.pdf')
prerr()
print('---cpdf_toFileEncryptedExt')
pycpdf.toFileEncryptedExt(pdf5, pycpdf.pdf40bit, [pycpdf.noEdit], 'owner', 'user', False, False, False, False, False, 'testoutputs/enc2.pdf')
prerr()
encpdf = pycpdf.fromFile('testoutputs/enc.pdf', 'user')
print('---cpdf_decryptPdf')
decrypted = pycpdf.decryptPdf(encpdf, 'user')
prerr()
encpdf2 = pycpdf.fromFile('testoutputs/enc.pdf', 'user')
print('---cpdf_decryptPdfOwner')
owner = pycpdf.decryptPdfOwner(encpdf2, 'owner')
prerr()
print('---cpdf_hasPermission')
hasperm = pycpdf.hasPermission(encpdf2, pycpdf.noEdit)
prerr()
print('---cpdf_encryptionKind')
encmethod = pycpdf.encryptionKind(encpdf2)

# CHAPTER 2. Merging and Splitting
pdf = pycpdf.fromFile('testinputs/cpdfmanual.pdf', '')
pdf2 = pycpdf.fromFile('testinputs/cpdfmanual.pdf', '')
print(pdf, pdf2)
merged = pycpdf.mergeSimple([pdf, pdf2])
pycpdf.toFile(merged, 'testoutputs/merged.pdf', False, False)
merged2 = pycpdf.merge([pdf, pdf2], True, False)
pycpdf.toFile(merged2, 'testoutputs/merged2.pdf', False, False)
same = pycpdf.mergeSame([pdf, pdf2, pdf], True, False, [pycpdf.even(pycpdf.all(pdf)), pycpdf.all(pdf2), pycpdf.odd(pycpdf.all(pdf))])
pycpdf.toFile(same, 'testoutputs/same.pdf', False, False)
selected = pycpdf.selectPages(pdf, pycpdf.even(pycpdf.all(pdf)))
pycpdf.toFile(selected, 'testoutputs/selected.pdf', False, False)

# CHAPTER 3. Pages
pdf = pycpdf.fromFile('testinputs/cpdfmanual.pdf', '')
r = pycpdf.all(pdf)
pycpdf.scalePages(pdf, r, 0.5, 0.7)
pycpdf.scaleToFit(pdf, r, 0.5, 0.7, 0.5)
pycpdf.scaleToFitPaper(pdf, r, pycpdf.a3landscape, 0.5)
pycpdf.scaleContents(pdf, r, (pycpdf.top, 10, 10), 1.0)
pycpdf.shiftContents(pdf, r, 100, -100)
pycpdf.rotate(pdf, r, 90)
pycpdf.rotateBy(pdf, r, 180)
pycpdf.rotateContents(pdf, r, 43.3)
pycpdf.upright(pdf, r)
pycpdf.hFlip(pdf, r)
pycpdf.vFlip(pdf, r)
pycpdf.crop(pdf, r, 100.0, 100.0, 400.0, 400.0)
pycpdf.removeCrop(pdf, r)
pycpdf.removeTrim(pdf, r)
pycpdf.removeArt(pdf, r)
pycpdf.removeBleed(pdf, r)
pycpdf.trimMarks(pdf, r)
pycpdf.showBoxes(pdf, r)
pycpdf.hardBox(pdf, r, "/MediaBox")

# CHAPTER 4. Encryption

# Encryption covered under Chapter 1 in cpdflib

# CHAPTER 5. Compression
pdf = pycpdf.fromFile('testinputs/cpdfmanual.pdf', '')
pycpdf.compress(pdf)
pycpdf.decompress(pdf)
pycpdf.squeezeInMemory(pdf)
pycpdf.toFile(pdf, 'testoutputs/squeezed.pdf', False, False)

# CHAPTER 6. Bookmarks

# Format: list of tuples. (level : int, page : int, text : string, openstatus : int/bool) 
existing_marks = pycpdf.getBookmarks(pdf)
print(existing_marks)
marks = [(0, 1, "new bookmark", True), (1, 3, "second, indented one", False)]
pycpdf.setBookmarks(pdf, marks)

# CHAPTER 7. Presentations

# Not included in the library version

# CHAPTER 8. Logos, Watermarks and Stamps
pycpdf.stampOn(pdf, pdf2, r)
pycpdf.stampUnder(pdf, pdf2, r)
pycpdf.stampExtended(pdf, pdf2, r, True, True, pycpdf.topLeft, False)
pycpdf.combinePages(pdf, pdf2)
pycpdf.addText(False, pdf, r, 'The text', (pycpdf.topLeft, 1.0, 0.0), 1.0, 10, pycpdf.timesRoman, 12, 0.5, 0.5, 0.5, False, False, False, 1.0, pycpdf.centreJustify, True, False, 'foo.pdf', 2.0, False)
pycpdf.addTextSimple(pdf, r, 'The text', (pycpdf.posCentre, 100.0, 200.0), pycpdf.timesRoman, 12.0)
pycpdf.removeText(pdf, r)
pycpdf.textWidth(pycpdf.timesRoman, 'Some text')

# CHAPTER 9. Multipage facilities
pdf = pycpdf.fromFile('testinputs/cpdfmanual.pdf', '')
pycpdf.twoUp(pdf)
pycpdf.twoUpStack(pdf)
r = pycpdf.all(pdf)
pycpdf.padBefore(pdf, r)
pycpdf.padAfter(pdf, r)
pycpdf.padEvery(pdf, 10)
pycpdf.padMultiple(pdf, 10)
pycpdf.padMultipleBefore(pdf, 10)
pycpdf.toFile(pdf, 'testoutputs/squeezed.pdf', False, False)

# CHAPTER 10. Annotations

# Not in the library version.

# CHAPTER 11. Document Information and Metadata
linearized = pycpdf.isLinearized('testinputs/cpdfmanual.pdf')
version = pycpdf.getVersion(pdf)
version2 = pycpdf.getMajorVersion(pdf)
title = pycpdf.getTitle(pdf)
print(f'title: {title}')
author = pycpdf.getAuthor(pdf)
print(f'author: {author}')
subject = pycpdf.getSubject(pdf)
print(f'subject: {subject}')
keywords = pycpdf.getKeywords(pdf)
print(f'keywords: {keywords}')
creator = pycpdf.getCreator(pdf)
print(f'creator: {creator}')
producer = pycpdf.getProducer(pdf)
print(f'producer: {producer}')
creationDate = pycpdf.getCreationDate(pdf)
print(f'creationDate: {creationDate}')
modificationDate = pycpdf.getModificationDate(pdf)
print(f'modificationDate: {modificationDate}')
titleXMP = pycpdf.getTitleXMP(pdf)
print(f'titleXMP: {titleXMP}')
authorXMP = pycpdf.getAuthorXMP(pdf)
print(f'authorXMP: {authorXMP}')
subjectXMP = pycpdf.getSubjectXMP(pdf)
print(f'subjectXMP: {subjectXMP}')
keywordsXMP = pycpdf.getKeywordsXMP(pdf)
print(f'keywordsXMP: {keywordsXMP}')
creatorXMP = pycpdf.getCreatorXMP(pdf)
print(f'creatorXMP: {creatorXMP}')
producerXMP = pycpdf.getProducerXMP(pdf)
print(f'producerXMP: {producerXMP}')
creationDateXMP = pycpdf.getCreationDateXMP(pdf)
print(f'creationDateXMP: {creationDateXMP}')
modificationDateXMP = pycpdf.getModificationDateXMP(pdf)
print(f'modificationDateXMP: {modificationDateXMP}')
pycpdf.setTitle(pdf, 'title')
pycpdf.setAuthor(pdf, 'author')
pycpdf.setSubject(pdf, 'subject')
pycpdf.setKeywords(pdf, 'keywords')
pycpdf.setCreator(pdf, 'creator')
pycpdf.setProducer(pdf, 'producer')
pycpdf.setCreationDate(pdf, 'now')
pycpdf.setModificationDate(pdf, 'now')
pycpdf.setTitleXMP(pdf, 'title')
pycpdf.setAuthorXMP(pdf, 'author')
pycpdf.setSubjectXMP(pdf, 'subject')
pycpdf.setKeywordsXMP(pdf, 'keywords')
pycpdf.setCreatorXMP(pdf, 'creator')
pycpdf.setProducerXMP(pdf, 'producer')
pycpdf.setCreationDateXMP(pdf, 'now')
pycpdf.setModificationDateXMP(pdf, 'now')
components = pycpdf.getDateComponents('now')
dateString = pycpdf.dateStringOfComponents(components)
rot = pycpdf.getPageRotation(pdf, 1)
hasBox = pycpdf.hasBox(pdf, 1, '/TrimBox')
mediaBox = pycpdf.getMediaBox(pdf, 1)
print(mediaBox)
cropBox = pycpdf.getCropBox(pdf, 1)
print(cropBox)
trimBox = pycpdf.getTrimBox(pdf, 1)
print(trimBox)
artBox = pycpdf.getArtBox(pdf, 1)
print(artBox)
bleedBox = pycpdf.getBleedBox(pdf, 1)
print(bleedBox)
pycpdf.setMediaBox(pdf, 1, 1.0, 1.0, 200.0, 200.0)
pycpdf.setCropBox(pdf, 1, 1.0, 1.0, 200.0, 200.0)
pycpdf.setTrimBox(pdf, 1, 1.0, 1.0, 200.0, 200.0)
pycpdf.setArtBox(pdf, 1, 1.0, 1.0, 200.0, 200.0)
pycpdf.setBleedBox(pdf, 1, 1.0, 1.0, 200.0, 200.0)
pycpdf.markTrapped(pdf)
pycpdf.markUntrapped(pdf)
pycpdf.markTrappedXMP(pdf)
pycpdf.markUntrappedXMP(pdf)
pycpdf.setPageLayout(pdf, pycpdf.singlePage)
pycpdf.setPageMode(pdf, pycpdf.useThumbs)
pycpdf.hideToolbar(pdf, True)
pycpdf.hideMenubar(pdf, False)
pycpdf.hideWindowUi(pdf, True)
pycpdf.fitWindow(pdf, True)
pycpdf.centerWindow(pdf, True)
pycpdf.displayDocTitle(pdf, True)
pycpdf.openAtPage(pdf, True, 5)
pycpdf.setMetadataFromFile(pdf, 'testinputs/metadata.txt')
pycpdf.setMetadataFromByteArray(pdf, 'data')
metadata = pycpdf.getMetadata(pdf)
pycpdf.removeMetadata(pdf)
pycpdf.createMetadata(pdf)
pycpdf.setMetadataDate(pdf, 'now')
labels = pycpdf.getPageLabels(pdf)
print(labels)
pycpdf.addPageLabels(pdf, (pycpdf.decimalArabic, "PRE-", 1, pycpdf.all(pdf)), False)
pycpdf.removePageLabels(pdf)
labelString = pycpdf.getPageLabelStringForPage(pdf, 1)

# CHAPTER 12. File Attachments
pycpdf.attachFile('testinputs/attach.txt', pdf)
pycpdf.attachFileToPage('testinputs/attach.txt', pdf, 1)
pycpdf.attachFileFromMemory('data', 'filename.txt', pdf)
pycpdf.attachFileToPageFromMemory('data', 'filename.txt', pdf, 1)
pycpdf.removeAttachedFiles(pdf)
attachments = pycpdf.getAttachments(pdf)

# CHAPTER 13. Images
images = pycpdf.getImageResolution(pdf, 300)
print(images)

# CHAPTER 14. Fonts
fonts = pycpdf.getFontInfo(pdf)
print(fonts)
pycpdf.removeFonts(pdf)
pycpdf.copyFont(pdf, pdf2, r, 1, "/Font")

# CHAPTER 15. Miscellaneous
pdf = pycpdf.fromFile('testinputs/cpdfmanual.pdf', '')
pycpdf.draft(pdf, r, True)
pycpdf.removeAllText(pdf, r)
pycpdf.blackText(pdf, r)
pycpdf.blackLines(pdf, r)
pycpdf.blackFills(pdf, r)
pycpdf.thinLines(pdf, r, 2.0)
pycpdf.copyId(pdf, pdf2)
pycpdf.removeId(pdf)
pycpdf.setVersion(pdf, 6)
pycpdf.removeDictEntry(pdf, '/Key')
pycpdf.removeClipping(pdf, pycpdf.all(pdf))
pycpdf.toFile(pdf, 'testoutputs/squeezed.pdf', False, False)

# CHAPTER UNDOC (To come in v2.4)
pdf = pycpdf.fromFile('testinputs/cpdfmanual.pdf', '')
pycpdf.addContent('content', True, pdf, pycpdf.all(pdf))
pycpdf.outputJSON('testoutputs/filename.txt', True, False, pdf)
pycpdf.OCGCoalesce(pdf)
pycpdf.OCGRename(pdf, 'one', 'two')
pycpdf.OCGOrderAll(pdf)
name = pycpdf.stampAsXObject(pdf, pycpdf.all(pdf), pdf2)
pycpdf.setDemo(True)
